import "./globals.css";
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import { Ubuntu } from '@next/font/google';

const ubuntu = Ubuntu({
  subsets: ['latin'],
  weight: ['400', '700'], 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={ubuntu.className}
      >
        <main className="flex flex-col">
        <Navbar />

        {children}

        <Footer />
        </main>
      </body>
    </html>
  );
}
